# Generated by Django 5.1.6 on 2025-02-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='up_images/')),
                ('price', models.CharField(max_length=150, verbose_name='Цена')),
                ('main_text', models.TextField(verbose_name='Текст')),
                ('star1', models.ImageField(blank=True, default='', null=True, upload_to='up_images/')),
                ('star2', models.ImageField(blank=True, default='', null=True, upload_to='up_images/')),
                ('star3', models.ImageField(blank=True, default='', null=True, upload_to='up_images/')),
                ('star4', models.ImageField(blank=True, default='', null=True, upload_to='up_images/')),
            ],
            options={
                'verbose_name': 'Картинка верхней части',
                'verbose_name_plural': 'Картинки верхней части',
            },
        ),
    ]
